# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: author_book_management_system_development

test:
  <<: *default
  database: author_book_management_system_test

production:
  <<: *default
  database: author_book_management_system_production
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>